f"""
[sources.basicmetrics_collect]
  type = "socket"
  mode = "unix_stream"
  path = "/tmp/unix_sockets/{data["agent"]["BasicMetrics"]["unix"]}"
  decoding.codec = "bytes"
#  max_length = 10485760
#[sinks.kong_forward]
#  type = "vector"
#  inputs = ["kong_collect"]
#  address = "{data["forwarder"]["host"]}:{data["forwarder"]["BasicMetrics"]["port"]}"
#  compression = true
[transforms.basicmetrics_metrics_reassemble]
  type = "reduce"
  inputs = ["basicmetrics_collect"]
#  starts_when = 'contains(string!(.message), "<start>")'
  ends_when = 'contains(string!(.message), "<end>")'
  [transforms.basicmetrics_metrics_reassemble.merge_strategies]
    message = "concat_raw"
[sinks.metrics_debug]
  inputs = ["basicmetrics_metrics_reassemble"]
  type = "console"
  encoding.codec = "json"
"""