stages:
  - pipeline
image: alpine:latest
hello-kitty:
  stage: pipeline
  script:
    - curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
    - yum -y install python3-pip
    - yum -y install nodejs
    - pip3 install semgrep
    - npm install n -g
    - n 16
    - npm install
    - npm run pipeline
