stages:
  - pipeline
image: alpine:latest
hello-kitty:
  stage: pipeline
  script:
    - sudo yum -y remove nodejs
    - sudo rm -r /etc/yum.repos.d/nodesource*.repo &&\
    - yum clean all
    - curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
    - sudo yum -y install python3-pip
    - sudo yum -y install nodejs
    - pip3 install semgrep
    - npm install n -g
    - sudo n 16
    - npm install
    - npm run pipeline
