f"""
[sources.loadbalancer_injest]
  type = "file"
  glob_minimum_cooldown_ms = 1000
  include = [ "/tmp/logs/*.log.gz","/tmp/logs/*.log" ]
  line_delimiter = "\\n"
  read_from = "beginning"
[transforms.loadbalancer_parse]
  inputs = ["loadbalancer_injest"]
  type = "remap"
  source = '''
    time = now()
    del(.file)
    del(.host)
    del(.source_type)
    del(.timestamp)
    . = parse_regex(.message, r'^(?P<type>\\S+) (?P<time0>\\S+) (?P<elb_name>\\S+) (?P<client_ip_port>\\S+) (?P<target_ip_port>\\S+) (?P<request_processing_time>\\S+) (?P<target_processing_time>\\S+) (?P<response_processing_time>\\S+) (?P<elb_status_code>\\d+) (?P<target_status_code>\\S+) (?P<received_bytes>\\d+) (?P<sent_bytes>\\d+) "(?P<request_method>[^ ]+) (?P<request_url>[^ ]+) (?P<request_protocol>[^"]+)" "(?P<user_agent>[^"]*)" (?P<ssl_cipher>\\S+) (?P<ssl_protocol>\\S+) (?P<target_group_arn>\\S+) "(?P<trace_id>[^"]*)" "(?P<domain_name>[^"]*)" "(?P<chosen_cert_arn>[^"]*)" (?P<matched_rule_priority>\\S+) (?P<timestamp>\\S+) "(?P<actions_executed>[^"]*)" "(?P<redirect_url>[^"]*)" "(?P<lambda_error_reason>[^"]*)" "(?P<target_port_list>[^"]*)" "(?P<target_status_code_list>[^"]*)" "(?P<classification>[^"]*)" "(?P<classification_reason>[^"]*)"') ?? null
    del(.message)
    del(.time0)
    .logstamp = format_timestamp!(time, "%Y-%m-%dT%H:%M:%S%.3f")
    .timestamp= parse_timestamp!(.timestamp, "%Y-%m-%dT%H:%M:%S.%fZ")
    .timestamp=format_timestamp!(.timestamp, "%Y-%m-%dT%H:%M:%S%.3f")
    .received_bytes = parse_int(.received_bytes) ?? -1
    .sent_bytes = parse_int(.sent_bytes) ?? -1
    .request_processing_time= parse_float(.request_processing_time) ?? -1
    .response_processing_time = parse_float(.response_processing_time) ?? -1
    .target_processing_time = parse_float(.target_processing_time) ?? -1
  '''
[sinks.loadbalancer_index]
    inputs = ["loadbalancer_parse"]
    type = "clickhouse"
    endpoint = "http://{data["indexer"]["host"]}:{data["indexer"]["http-port"]}"
    database = "default"
    table = "elb"
    skip_unknown_fields = true
    compression = "gzip"
    auth.strategy = "basic"
    auth.user = "default"
    auth.password = "{data["indexer"]["password"]}"
#[sinks.loadbalancer_debug]
#    inputs = ["loadbalancer_parse"]
#    type = "console"
#    encoding.codec = "json"
"""