services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: BykeaAPIGateway_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    restart: always
  redis:
    image: redis:7.0.15-alpine
    container_name: BykeaAPIGateway_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: always
  #elasticsearch:
  #  image: elasticsearch:8.13.4
  #  container_name: BykeaAPIGateway_elastic
  #  ports: 
  #    - "9200:9200"
  #logstash:
  #  image: logstash:8.13.4
  #  container_name: BykeaAPIGateway_logstash
  #  ports: 
  #    - "5775:5775"
  #kibana:
  #  image: kibana:8.13.4
  #  container_name: BykeaAPIGateway_kibana
  #  ports:
  #    - "5601:5601"