[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[91m0[94m---[31mO[0m	Beginnging!
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m 0[34m=[31mo[0m	Beginnging!
[91m  0[0m	connected to container engine
[31m o[34m=[91m0[0m	loaded external configs
[31mO[94m---[91m0[0m	loaded internal configs
[31m0[94m---[91mO[0m	loaded common parameters
[31m 0[34m=[91mo[0m	init section done
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m  0[0m	Beginnging!
[31m o[34m=[91m0[0m	connected to container engine
[31mO[94m---[91m0[0m	loaded external configs
[31m0[94m---[91mO[0m	loaded internal configs
[31m 0[34m=[91mo[0m	loaded common parameters
[31m  0[0m	init section done
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[31m o[34m=[91m0[0m	Beginnging!
[31mO[94m---[91m0[0m	connected to container engine
[31m0[94m---[91mO[0m	loaded external configs
[31m 0[34m=[91mo[0m	loaded internal configs
[31m  0[0m	loaded common parameters
[91m o[34m=[31m0[0m	init section done
[91mO[94m---[31m0[0m	killed old residual containers
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31mO[94m---[91m0[0m	Beginnging!
[31m0[94m---[91mO[0m	connected to container engine
[31m 0[34m=[91mo[0m	loaded external configs
[31m  0[0m	loaded internal configs
[91m o[34m=[31m0[0m	loaded common parameters
[91mO[94m---[31m0[0m	init section done
[91m0[94m---[31mO[0m	killed old residual containers
[91m 0[34m=[31mo[0m	network created
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31m0[94m---[91mO[0m	Beginnging!
[31m 0[34m=[91mo[0m	connected to container engine
[31m  0[0m	loaded external configs
[91m o[34m=[31m0[0m	loaded internal configs
[91mO[94m---[31m0[0m	loaded common parameters
[91m0[94m---[31mO[0m	init section done
[91m 0[34m=[31mo[0m	killed old residual containers
[91m  0[0m	network created
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m 0[34m=[91mo[0m	Beginnging!
[31m  0[0m	connected to container engine
[91m o[34m=[31m0[0m	loaded external configs
[91mO[94m---[31m0[0m	loaded internal configs
[91m0[94m---[31mO[0m	loaded common parameters
[91m 0[34m=[31mo[0m	init section done
[91m  0[0m	killed old residual containers
[31m o[34m=[91m0[0m	network created
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m  0[0m	Beginnging!
[91m o[34m=[31m0[0m	connected to container engine
[91mO[94m---[31m0[0m	loaded external configs
[91m0[94m---[31mO[0m	loaded internal configs
[91m 0[34m=[31mo[0m	loaded common parameters
[91m  0[0m	init section done
[31m o[34m=[91m0[0m	killed old residual containers
[31mO[94m---[91m0[0m	network created
[31m0[94m---[91mO[0m	spun up postgres
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[91m o[34m=[31m0[0m	Beginnging!
[91mO[94m---[31m0[0m	connected to container engine
[91m0[94m---[31mO[0m	loaded external configs
[91m 0[34m=[31mo[0m	loaded internal configs
[91m  0[0m	loaded common parameters
[31m o[34m=[91m0[0m	init section done
[31mO[94m---[91m0[0m	killed old residual containers
[31m0[94m---[91mO[0m	network created
[31m 0[34m=[91mo[0m	spun up postgres
[31m  0[0m	spun up redis
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91mO[94m---[31m0[0m	Beginnging!
[91m0[94m---[31mO[0m	connected to container engine
[91m 0[34m=[31mo[0m	loaded external configs
[91m  0[0m	loaded internal configs
[31m o[34m=[91m0[0m	loaded common parameters
[31mO[94m---[91m0[0m	init section done
[31m0[94m---[91mO[0m	killed old residual containers
[31m 0[34m=[91mo[0m	network created
[31m  0[0m	spun up postgres
[91m o[34m=[31m0[0m	spun up redis
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91m0[94m---[31mO[0m	Beginnging!
[91m 0[34m=[31mo[0m	connected to container engine
[91m  0[0m	loaded external configs
[31m o[34m=[91m0[0m	loaded internal configs
[31mO[94m---[91m0[0m	loaded common parameters
[31m0[94m---[91mO[0m	init section done
[31m 0[34m=[91mo[0m	killed old residual containers
[31m  0[0m	network created
[91m o[34m=[31m0[0m	spun up postgres
[91mO[94m---[31m0[0m	spun up redis
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m 0[34m=[31mo[0m	Beginnging!
[91m  0[0m	connected to container engine
[31m o[34m=[91m0[0m	loaded external configs
[31mO[94m---[91m0[0m	loaded internal configs
[31m0[94m---[91mO[0m	loaded common parameters
[31m 0[34m=[91mo[0m	init section done
[31m  0[0m	killed old residual containers
[91m o[34m=[31m0[0m	network created
[91mO[94m---[31m0[0m	spun up postgres
[91m0[94m---[31mO[0m	spun up redis
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m  0[0m	Beginnging!
[31m o[34m=[91m0[0m	connected to container engine
[31mO[94m---[91m0[0m	loaded external configs
[31m0[94m---[91mO[0m	loaded internal configs
[31m 0[34m=[91mo[0m	loaded common parameters
[31m  0[0m	init section done
[91m o[34m=[31m0[0m	killed old residual containers
[91mO[94m---[31m0[0m	network created
[91m0[94m---[31mO[0m	spun up postgres
[91m 0[34m=[31mo[0m	spun up redis
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[31m o[34m=[91m0[0m	Beginnging!
[31mO[94m---[91m0[0m	connected to container engine
[31m0[94m---[91mO[0m	loaded external configs
[31m 0[34m=[91mo[0m	loaded internal configs[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J[H[2J[3J
[31m  0[0m	loaded common parameters
[91m o[34m=[31m0[0m	init section done
[91mO[94m---[31m0[0m	killed old residual containers
[91m0[94m---[31mO[0m	network created
[91m 0[34m=[31mo[0m	spun up postgres
[91m  0[0m	spun up redis
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31mO[94m---[91m0[0m	Beginnging!
[31m0[94m---[91mO[0m	connected to container engine
[31m 0[34m=[91mo[0m	loaded external configs
[31m  0[0m	loaded internal configs
[91m o[34m=[31m0[0m	loaded common parameters
[91mO[94m---[31m0[0m	init section done
[91m0[94m---[31mO[0m	killed old residual containers
[91m 0[34m=[31mo[0m	network created
[91m  0[0m	spun up postgres
[31m o[34m=[91m0[0m	spun up redis
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31m0[94m---[91mO[0m	Beginnging!
[31m 0[34m=[91mo[0m	connected to container engine
[31m  0[0m	loaded external configs
[91m o[34m=[31m0[0m	loaded internal configs
[91mO[94m---[31m0[0m	loaded common parameters
[91m0[94m---[31mO[0m	init section done
[91m 0[34m=[31mo[0m	killed old residual containers
[91m  0[0m	network created
[31m o[34m=[91m0[0m	spun up postgres
[31mO[94m---[91m0[0m	spun up redis
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m 0[34m=[91mo[0m	Beginnging!
[31m  0[0m	connected to container engine
[91m o[34m=[31m0[0m	loaded external configs
[91mO[94m---[31m0[0m	loaded internal configs
[91m0[94m---[31mO[0m	loaded common parameters
[91m 0[34m=[31mo[0m	init section done
[91m  0[0m	killed old residual containers
[31m o[34m=[91m0[0m	network created
[31mO[94m---[91m0[0m	spun up postgres
[31m0[94m---[91mO[0m	spun up redis
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m  0[0m	Beginnging!
[91m o[34m=[31m0[0m	connected to container engine
[91mO[94m---[31m0[0m	loaded external configs
[91m0[94m---[31mO[0m	loaded internal configs
[91m 0[34m=[31mo[0m	loaded common parameters
[91m  0[0m	init section done
[31m o[34m=[91m0[0m	killed old residual containers
[31mO[94m---[91m0[0m	network created
[31m0[94m---[91mO[0m	spun up postgres
[31m 0[34m=[91mo[0m	spun up redis
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[91m o[34m=[31m0[0m	Beginnging!
[91mO[94m---[31m0[0m	connected to container engine
[91m0[94m---[31mO[0m	loaded external configs
[91m 0[34m=[31mo[0m	loaded internal configs
[91m  0[0m	loaded common parameters
[31m o[34m=[91m0[0m	init section done
[31mO[94m---[91m0[0m	killed old residual containers
[31m0[94m---[91mO[0m	network created
[31m 0[34m=[91mo[0m	spun up postgres
[31m  0[0m	spun up redis
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91mO[94m---[31m0[0m	Beginnging!
[91m0[94m---[31mO[0m	connected to container engine
[91m 0[34m=[31mo[0m	loaded external configs
[91m  0[0m	loaded internal configs
[31m o[34m=[91m0[0m	loaded common parameters
[31mO[94m---[91m0[0m	init section done
[31m0[94m---[91mO[0m	killed old residual containers
[31m 0[34m=[91mo[0m	network created
[31m  0[0m	spun up postgres
[91m o[34m=[31m0[0m	spun up redis
[91mO[94m---[31m0[0m
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91m0[94m---[31mO[0m	Beginnging!
[91m 0[34m=[31mo[0m	connected to container engine
[91m  0[0m	loaded external configs
[31m o[34m=[91m0[0m	loaded internal configs
[31mO[94m---[91m0[0m	loaded common parameters
[31m0[94m---[91mO[0m	init section done
[31m 0[34m=[91mo[0m	killed old residual containers
[31m  0[0m	network created
[91m o[34m=[31m0[0m	spun up postgres
[91mO[94m---[31m0[0m	spun up redis
[91m0[94m---[31mO[0m
[91m 0[34m=[31mo[0m
[91m  0[0m
[31m o[34m=[91m0[0m
[31mO[94m---[91m0[0m
[31m0[94m---[91mO[0m
[31m 0[34m=[91mo[0m
[31m  0[0m
[91m o[34m=[31m0[0m
[91mO[94m---[31m0[0m
