input {{
  udp {{
    port => {logstash_port}
    codec => json
  }}
}}
output {{
  elasticsearch {{
    hosts => ["{elasticsearch_host}:{elasticsearch_port}"]
    ssl => true
    ssl_certificate_verification => false
    cacert => "/usr/share/logstash/certificates/http_ca.crt"
    index => "http-%{{+YYYY.MM.dd}}"
    user => "{logstash_user}"
    password => "{logstash_pass}"
  }}
}}