input {{
    tcp {{
        port => {forwarder_port}
        codec => plain
    }}
}}
filter {{
    mutate {{
        add_field => {{
            "kong_route"=>   "%{{[route][name]}}"
            "kong_service"=> "%{{[service][name]}}"
        }}
        remove_field => ["route","service","latencies","tries","upstream_uri","latencies","request.url"]
    }}
    ruby {{
        code => '
               require "securerandom"
               parsed_json= JSON.parse(event.get("message"))
               pri=         (16 * 8) + 2
               ver=         event.get("@version")
               ts=          event.get("@timestamp").time.strftime("%Y-%m-%d %H:%M:%S")
               hos=         format("%s:%d/%s",event.get("host"),event.get("port"),parsed_json["__SId"])
               sr=          "KongHTTP"
               pid=         "TODO"
               msg=         SecureRandom.uuid
               txt=         event.get("message")
               event.set("message",format("<%d>%s %s %s %s %s %s body=%s",pri,ver,ts,hos,sr,pid,msg,txt))
        '
    }}
}}
output {{
    stdout {{
        codec => plain {{
            format => "%{{message}}"
        }}
    }}
    file {{
        path => "/tmp/kong/logfile.log"
        max_size => "1GB"
        max_files => 4
        flush_interval => 5
    }}
    # s3 {{
    #   access_key_id => "YOUR_AWS_ACCESS_KEY"
    #   secret_access_key => "YOUR_AWS_SECRET_KEY"
    #   bucket => "your-s3-bucket-name"
    #   region => "your-region"
    #   time_file => 5
    #   prefix => "logs/"
    # }}
}}
