input {{
    tcp {{
        port => {forwarder_port}
        codec => plain
    }}
}}
filter {{
    mutate {{
        add_field => {{
            "kong_route"=>   "%{{[route][name]}}"
            "kong_service"=> "%{{[service][name]}}"
        }}
        remove_field => ["route","service","latencies","tries","upstream_uri","latencies","request.url"]
    }}
    ruby {{
        code => '
               require "securerandom"
               parsed_json= JSON.parse(event.get("message"))
               event.set("pri", (16 * 8) + 2)
               event.set("ver", event.get("@version"))
               event.set("ts",  event.get("@timestamp").time.strftime("%Y-%m-%d %H:%M:%S"))
               event.set("hos", format("%s:%d/%s",event.get("host"),event.get("port"),parsed_json["__SId"]))
               event.set("sr",  "KongHTTP")
               event.set("pid", "TODO")
               event.set("msg", SecureRandom.uuid)
               event.set("txt", format("body=%s",event.get("message")))
               event.set("message",format("<%d>%s %s %s %s %s %s body=%s\n",pri,ver,ts,hos,sr,pid,msg,txt))
        '
    }}
}}
output {{
    stdout {{
        codec => plain {{
            format => "%{{message}}"
        }}
    }}
    syslog {{
        host => "{manager_host}"
        port => {manager_syslog_port}
        protocol => "tcp"
        rfc => "rfc5424"
        priority => "%{{pri}}"
        sourcehost => "%{{hos}}"
        appname => "%{{sr}}"
        procid => "%{{pid}}"
        msgid => "%{{msg}}"
        message => "%{{txt}}"
    }}
    # s3 {{
    #   access_key_id => "YOUR_AWS_ACCESS_KEY"
    #   secret_access_key => "YOUR_AWS_SECRET_KEY"
    #   bucket => "your-s3-bucket-name"
    #   region => "your-region"
    #   time_file => 5
    #   prefix => "logs/"
    # }}
}}
