#=================================
#  pipeline.workers: 3
#  pipeline.batch.size: 125
#  pipeline.batch.delay: 50
#  pipeline.ordered: false
#  queue.type: "memory"
#  queue.max_bytes: 4gb
#=================================
input {
  udp {
    port => 65001
    codec => "json"
    buffer_size => 65535
    queue_size => 32768
    receive_buffer_bytes => 2147450880
    workers => 3
  }
}
output {
  elasticsearch {
    hosts => ["http://elk-prod.bykea.prod:9200"]
    user => "elastic"
    password => "ASKDEVOPS"
    index => "incidence-%{+YYYY.MM.dd}"
    retry_initial_interval => 1
  }
  file {
    path => "/tmp/log.0"
    codec => "json"
  }
}