#=================================
#  pipeline.workers: 1
#  pipeline.batch.size: 125
#  pipeline.batch.delay: 50
#  pipeline.ordered: true
#=================================
input {
  udp {
    port => 65001
    codec => "json"
  }
}
output {
  elasticsearch {
    hosts => ["http://elk-prod.bykea.prod:9200"]
    user => "elastic"
    password => "ASK DEVOPS"
    index => "incidence-%{+YYYY.MM.dd}"
  }
  file {
    path => "/tmp/file.log"
    codec => "plain"
    flush_interval => 0
  }
}