#=================================
#  pipeline.workers: 1
#  pipeline.batch.size: 125
#  pipeline.batch.delay: 50
#  pipeline.unsafe_shutdown: false
#  pipeline.ordered: true
#=================================
input {
  tcp {
    port => 65000
    codec => "plain"
  }
}
output {
  elasticsearch {
    hosts => ["http://elk-prod.bykea.prod:9200"]
    username => "filebeat_client"
    password => "ASK_DEVOPS!"
    index => "Incidence-%{+YYYY.MM.dd}"
  }
  stdout {codec => rubydebug}
}