#=================================
#  pipeline.workers: 1
#  pipeline.batch.size: 125
#  pipeline.batch.delay: 50
#  pipeline.ordered: true
#=================================
input {
  udp {
    port => 65000
    codec => "plain"
  }
}
output {
  file {
    path => "/tmp/file.log"
    codec => "plain"
    flush_interval => 0
  }
}