- pipeline.id: enabled_1.debug.conf
  path.config: "/usr/share/logstash/pipeline/enabled_1.debug.conf"
  pipeline.workers: 1
  pipeline.batch.size: 125
  pipeline.batch.delay: 50
  pipeline.unsafe_shutdown: false
  pipeline.ordered: true
