{
 "title": "Anomalies",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top Users by Traffic Rate",
   "type": "xychart",
   "description": "Displays users generating the highest request rates per minute, helping identify accounts with unusually high traffic that may indicate anomalous or suspicious activity.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    date_trunc('minute', timestamp) as bucket,\n    JSONExtractString(request.headers,'x-app-user-id') as userid,\n    COUNT(timestamp) as rpm,\n    --reinterpretAsUInt256(reverse(unhex(userid)))%65535 as colorid,\n    rpm as colorid,\n    rpm/1000 as sizeid\nFROM kong\nWHERE $__timeFilter(timestamp) AND JSONExtractString(request.headers,'x-app-user-id') != ''\nGROUP BY bucket,userid\nORDER BY rpm DESC\nLIMIT 5000"
    }
   ]
  },
  {
   "title": "Rare Response Header Keys",
   "type": "piechart",
   "description": "Displays the distribution of unique response header keys to highlight uncommon or potentially anomalous headers in API responses.",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH keys AS (\n    SELECT JSONExtractKeys(response.headers) AS key \n    FROM kong\n    WHERE $__timeFilter(timestamp)\n),\nranked_keys AS (\n    SELECT\n        key,\n        1/COUNT(*) as count\n    FROM keys\n    ARRAY JOIN key\n    GROUP BY key\n    ORDER BY count DESC\n)\nSELECT *\nFROM ranked_keys"
    }
   ]
  },
  {
   "title": "Unusual Request Header Keys",
   "type": "piechart",
   "description": "Displays the distribution of unusual request header keys, helping identify rare or potentially suspicious headers in incoming traffic.",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH keys AS (\n    SELECT JSONExtractKeys(request.headers) AS key \n    FROM kong\n    WHERE $__timeFilter(timestamp)\n),\nranked_keys AS (\n    SELECT\n        key,\n        1/COUNT(*) as count\n    FROM keys\n    ARRAY JOIN key\n    GROUP BY key\n    ORDER BY count DESC\n)\nSELECT *\nFROM ranked_keys"
    }
   ]
  },
  {
   "title": "Request Path Anomalies",
   "type": "piechart",
   "description": "Displays the distribution of unusual request paths detected, helping identify potentially suspicious or abnormal access patterns.",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH keys AS (\n    SELECT request.uri AS key \n    FROM kong\n    WHERE $__timeFilter(timestamp) and request.path = '~'\n),\nranked_keys AS (\n    SELECT\n        key,\n        1/COUNT(*) as count\n    FROM keys\n    GROUP BY key\n    ORDER BY count DESC\n)\nSELECT *\nFROM ranked_keys"
    }
   ]
  }
 ]
}