{
 "title": "Requests By Traffic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "interval", "query": "1,5,15,30,45,60" },
   { "name": "bucket", "query": "SECOND,MINUTE,HOUR" },
   { "name": "query0", "query": "AND 1=1" }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Shows request throughput over time, broken down by user type (partner, passenger, unknown), helping identify traffic patterns and spikes across different user categories.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n    COUNT(CASE WHEN JSONExtractRaw(request.headers, 'x-app-user-type') = '\"partner\"' THEN 1 END) as `partner`,\n    COUNT(CASE WHEN JSONExtractRaw(request.headers, 'x-app-user-type') = '\"passenger\"' THEN 1 END) as `passenger`,\n    COUNT(CASE WHEN JSONExtractRaw(request.headers, 'x-app-user-type') NOT IN ('\"passenger\"','\"partner\"') THEN 1 END) as `unknown`,\n    COUNT(*) as total,\n    1000 as `1k Line`,\n    1000000 as `1m Line`\nFROM kong\nWHERE $__timeFilter(timestamp) ${query0}\nGROUP BY time_bucket\nORDER BY time_bucket DESC;"
    }
   ]
  },
  {
   "title": "Authenticated Users",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(DISTINCT If(\n    JSONExtractRaw(request.headers, 'x-app-user-type') = '\"partner\"',\n    JSONExtractString(request.headers, 'x-app-user-id'),\n    NULL\n  )) AS `Partners`,\n  COUNT(DISTINCT If(\n    JSONExtractRaw(request.headers, 'x-app-user-type') = '\"passenger\"',\n    JSONExtractString(request.headers, 'x-app-user-id'),\n    NULL\n  )) AS `Passengers`,\n  COUNT(DISTINCT If(\n    JSONExtractRaw(request.headers, 'x-app-user-type') NOT IN ('\"partner\"', '\"passenger\"'),\n    JSONExtractString(request.headers, 'x-app-user-id'),\n    NULL\n  )) AS `Uknown Users`,\n  COUNT(DISTINCT\n    JSONExtractString(request.headers, 'x-app-user-id')\n  ) AS `Max`\nFROM kong\nWHERE $__timeFilter(timestamp) ${query0}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n    max(latencies.proxy) as \"max proxy\",\n    min(latencies.proxy) as \"min proxy\",\n    avg(latencies.proxy) as \"avg proxy\",\n    max(latencies.kong) as \"max internal\",\n    min(latencies.kong) as \"min internal\",\n    avg(latencies.kong) as \"avg internal\",\n    max(latencies.receive) as \"max receive\",\n    min(latencies.receive) as \"min recieve\",\n    avg(latencies.receive) as \"avg recieve\",\n    max(latencies.request) as \"max request\",\n    min(latencies.request) as \"min request\",\n    avg(latencies.request) as \"avg request\",\n    500 as `500ms Line`,\n    1000 as `1s Line`,\n    10000 as `10s Line`,\n    60000 as `1m Line`\nFROM kong\nWHERE $__timeFilter(timestamp) ${query0}\nGROUP BY time_bucket\nORDER BY time_bucket DESC;"
    }
   ]
  },
  {
   "title": "Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n    max(response.size) as `max response`,\n    min(response.size) as `min response`,\n    avg(response.size) as `avg response`,\n    max(request.size) as `max request`,\n    min(request.size) as `min request`,\n    avg(request.size) as `avg request`,\n    1024 as `1Kb line`,\n    10240 as `10Kb line`,\n    1048576 as `1Mb line`,\n    10485760 as `10Mb line`\nFROM kong\nWHERE $__timeFilter(timestamp) ${query0}\nGROUP BY time_bucket\nORDER BY time_bucket DESC;"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH user_agents AS (\n    SELECT \n        timestamp,\n        toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n        JSONExtractRaw(request.headers, 'user-agent') as ua\n    FROM kong\n    WHERE $__timeFilter(timestamp) ${query0}\n),\nclassified_data AS (SELECT \n    time_bucket as time,\n    CASE \n        WHEN match(ua, 'BYKEA.*iOS|CFNetwork.*Darwin|iPhone') THEN 'IOS'\n        WHEN match(ua, 'Dalvik.*|okhttp.*') THEN 'ANDROID'\n        WHEN match(ua, 'Mozilla\\/') THEN 'BROWSER'\n        ELSE 'OTHERS/TOOLS'\n    END as category,\n    -- OS Version extraction\n    CASE \n        -- iOS patterns\n        WHEN match(ua, 'BYKEA/[0-9]+.[0-9]+.[0-9]+ \\(.+?iOS .+?\\) .+') \n            THEN extractAll(ua, '(iOS .+)?\\)')[1]\n        WHEN match(ua, '.*?/[0-9]+ CFNetwork.*? Darwin.*?') \n            THEN extractAll(ua, '(Darwin.+?)\"')[1]\n        WHEN match(ua, 'BYKEA/[0-9]+.[0-9]+.[0-9]+ \\(iPhone')\n            THEN extractAll(ua, '(iOS .+?);')[1]\n        -- Android patterns\n        WHEN match(ua, 'Dalvik/.*? \\(.*\\)\"') \n            THEN extractAll(ua, '(Android [0-9.]+?);')[1]\n        -- Browser pattern\n        WHEN match(ua, 'Mozilla\\/') \n            THEN extractAll(ua, 'Mozilla\\/.*?(\\(.*?\\))')[1]\n        ELSE 'UNKNOWN'\n    END as OS_VERSION,\n    -- HTTP Client extraction\n    CASE \n        -- iOS patterns\n        WHEN match(ua, 'BYKEA/[0-9]+.[0-9]+.[0-9]+ \\(.+?iOS .+?\\) .+') \n            THEN extractAll(ua, '\\)(.+?)\"')[1]\n        WHEN match(ua, '.*?/[0-9]+ CFNetwork.*? Darwin.*?') \n            THEN extractAll(ua, '(CFNetwork.+?) ')[1]\n        -- Android patterns\n        WHEN match(ua, 'okhttp\\/([0-9.]+)') \n            THEN extractAll(ua, 'okhttp\\/([0-9.]+)')[1]\n        -- Browser pattern\n        WHEN match(ua, 'Mozilla\\/') \n            THEN extractAll(ua, '(Mozilla\\/.+?)\\(')[1]\n        ELSE '-'\n    END as HTTP_CLIENT,\n    CASE \n        -- iOS patterns\n        WHEN match(ua, 'BYKEA/[0-9]+.[0-9]+.[0-9]+ \\(.+?iOS .+?\\) .+') THEN 'IPhone'\n        WHEN match(ua, '.*?/[0-9]+ CFNetwork.*? Darwin.*?') THEN 'Apple'\n        WHEN match(ua, 'BYKEA/[0-9]+.[0-9]+.[0-9]+ \\(iPhone') THEN 'IPhone'\n        -- Android patterns\n        WHEN match(ua, 'Dalvik/.*? \\(.*\\)\"') \n            THEN extractAll(ua, 'Android [0-9.]+?;(.*)(Build)|(MIUI)\\/')[1]\n        WHEN match(ua, 'okhttp\\/([0-9.]+)') THEN 'GENERIC'\n        -- Browser pattern\n        WHEN match(ua, 'Mozilla\\/') THEN 'GENERIC'\n        ELSE 'UNKNOWN'\n    END as DEVICE,\n    ua as possible_values\nFROM user_agents)\n\nSELECT category,count(category) FROM (SELECT * FROM classified_data) GROUP BY category;"
    }
   ]
  },
  {
   "title": "By Path",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 20 },
   "targets": [
    {
     "rawSql": "WITH ranked_values AS (\n  SELECT\n    request.path as possible_values\n  FROM kong\n  WHERE $__timeFilter(timestamp) ${query0}\n  GROUP BY possible_values\n  ORDER BY COUNT(*) DESC\n  LIMIT 20\n),\ntime_series_data AS (\n  SELECT \n    toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n    request.path as app_version,\n    COUNT(*) as request_count\n  FROM kong\n  WHERE $__timeFilter(timestamp) ${query0}\n  GROUP BY time_bucket, app_version\n  ORDER BY request_count ASC\n)\nSELECT \n  time_bucket,\n  request_count as \" \",\n  CASE \n    WHEN app_version IN (SELECT possible_values FROM ranked_values) \n    THEN app_version \n    ELSE 'OTHER' \n  END as possible_values\nFROM time_series_data\nORDER BY time_bucket ASC, request_count ASC"
    }
   ]
  },
  {
   "title": "By Version",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "WITH ranked_values AS (\n  SELECT\n    JSONExtractRaw(request.headers, 'x-app-version') as possible_values\n  FROM kong\n  WHERE $__timeFilter(timestamp) ${query0}\n  GROUP BY possible_values\n  ORDER BY COUNT(*) DESC\n  LIMIT 25\n),\ntime_series_data AS (\n  SELECT \n    toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n    JSONExtractRaw(request.headers, 'x-app-version') as app_version,\n    COUNT(*) as request_count\n  FROM kong\n  WHERE $__timeFilter(timestamp) ${query0}\n  GROUP BY time_bucket, app_version\n)\nSELECT \n  time_bucket,\n  request_count as \" \",\n  CASE \n    WHEN app_version IN (SELECT possible_values FROM ranked_values) \n    THEN app_version \n    ELSE 'OTHER' \n  END as possible_values\nFROM time_series_data\nORDER BY time_bucket ASC, request_count DESC"
    }
   ]
  },
  {
   "title": "LogTime",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n    max(diffstamp)/1000 as max_value_seconds,\n    min(diffstamp)/1000 as min_value_seconds,\n    avg(diffstamp)/1000 as avg_value_seconds,\n    10 as `10 Second Line`,\n    60 as `1 Minute Line`,\n    3600 as `1 Hour Line`\nFROM kong\nWHERE $__timeFilter(timestamp) ${query0}\nGROUP BY time_bucket\nORDER BY time_bucket DESC;"
    }
   ]
  },
  {
   "title": "Status Codes Served",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "WITH ranked_values AS (\n  SELECT\n    DISTINCT response.status as possible_values,\n    count(response.status) as rank_order\n  FROM\n    kong\n  WHERE\n    $__timeFilter(timestamp) ${query0}\n  GROUP BY\n    response.status\n  ORDER BY\n    rank_order DESC\n  LIMIT\n    20\n),\nranked_accumulation AS (\n  SELECT \n      toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n      toString(response.status) as possible_values,\n      COUNT(response.status) as rank_order\n  FROM\n      kong\n  WHERE\n      $__timeFilter(timestamp) ${query0} AND\n      response.status IN (SELECT possible_values FROM ranked_values)\n  GROUP BY\n      response.status,\n      time_bucket\n),\nother_accumulation AS (\n  SELECT \n      toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n      'OTHER' as possible_values,\n      COUNT(response.status) as rank_order\n  FROM\n      kong\n  WHERE\n      $__timeFilter(timestamp) ${query0} AND\n      response.status NOT IN (SELECT possible_values FROM ranked_values)\n  GROUP BY\n      time_bucket\n),\naccumulated_results AS ( SELECT * FROM other_accumulation UNION ALL SELECT * FROM ranked_accumulation)\nSELECT time_bucket,rank_order as \" \",possible_values FROM accumulated_results ORDER BY time_bucket ASC, rank_order DESC"
    }
   ]
  },
  {
   "title": "Status Codes From Service",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "WITH ranked_values AS (\n  SELECT\n    DISTINCT response.upstream as possible_values,\n    count(response.upstream) as rank_order\n  FROM\n    kong\n  WHERE\n    $__timeFilter(timestamp) ${query0}\n  GROUP BY\n    response.upstream\n  ORDER BY\n    rank_order DESC\n  LIMIT\n    20\n),\nranked_accumulation AS (\n  SELECT \n      toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n      toString(response.upstream) as possible_values,\n      COUNT(response.upstream) as rank_order\n  FROM\n      kong\n  WHERE\n      $__timeFilter(timestamp) ${query0} AND\n      response.upstream IN (SELECT possible_values FROM ranked_values)\n  GROUP BY\n      response.upstream,\n      time_bucket\n),\nother_accumulation AS (\n  SELECT \n      toStartOfInterval(timestamp, INTERVAL ${interval} ${bucket}) as time_bucket,\n      'OTHER' as possible_values,\n      COUNT(response.upstream) as rank_order\n  FROM\n      kong\n  WHERE\n      $__timeFilter(timestamp) ${query0} AND\n      response.upstream NOT IN (SELECT possible_values FROM ranked_values)\n  GROUP BY\n      time_bucket\n),\naccumulated_results AS ( SELECT * FROM other_accumulation UNION ALL SELECT * FROM ranked_accumulation)\nSELECT time_bucket,rank_order as \" \",possible_values FROM accumulated_results ORDER BY time_bucket ASC, rank_order DESC"
    }
   ]
  }
 ]
}