input {{
  udp {{
    port => {logstash_port}
    codec => json
  }}
  tcp {{
    port => {logstash_port}
    codec => json
  }}
  syslog {{
    port => {logstash_syslog_port}
    codec => cef
    syslog_field => "syslog"
    grok_pattern => "<%{POSINT:priority}>%{SYSLOGTIMESTAMP:timestamp} CUSTOM GROK HERE"
  }}
  
}}
output {{
  elasticsearch {{
    hosts => ["{elasticsearch_host}:{elasticsearch_port}"]
    ssl => true
    ssl_certificate_verification => false
    cacert => "/usr/share/logstash/certificates/http_ca.crt"
    index => "http-%{{+YYYY.MM.dd}}"
    user => "{logstash_user}"
    password => "{logstash_pass}"
  }}
}}