input {{
    tcp {{
        port => {forwarder_port}
        codec => json
    }}
}}
filter {{
    mutate {{
        add_field => {{
            "kong_route"=>   "%{{[route][name]}}"
            "kong_service"=> "%{{[service][name]}}"
        }}
        remove_field => ["route","service","latencies","tries","upstream_uri","latencies","request.url"]
    }}
}}
output {{
    stdout {{
        codec => rubydebug
    }}
    file {{
        path => "/tmp/logfile.log"
        codec => "line"
    }}
}}