input {{
    tcp {{
        port => {forwarder_port}
        codec => json
    }}
}}
filter {{
    mutate {{
        add_field => {{
            "kong_route"=>   "%{{[route][name]}}"
            "kong_service"=> "%{{[service][name]}}"
        }}
        remove_field => ["route","service","latencies","tries","upstream_uri","latencies","request.url"]
    }}
    ruby {{
        code => 'event.set("formatted_message", "KongHTTP " + event.get("formatted_message").to_json)'
    }}
}}
output {{
    stdout {{
        codec => rubydebug
    }}
    tcp {{
        host => "127.0.0.1"
        port => 1122
    }}
    # Optionally, you can send to S3 or other outputs
    # s3 {{
    #   access_key_id => "YOUR_AWS_ACCESS_KEY"
    #   secret_access_key => "YOUR_AWS_SECRET_KEY"
    #   bucket => "your-s3-bucket-name"
    #   region => "your-region"
    #   time_file => 5
    #   prefix => "logs/"
    # }}
}}