input {{
    tcp {{
        port => {forwarder_port}
        codec => json
    }}
}}
filter {{
    mutate {{
        add_field => {{
            "kong_route"=>   "%{{[route][name]}}"
            "kong_service"=> "%{{[service][name]}}"
        }}
        remove_field => ["route","service","latencies","tries","upstream_uri","latencies","request.url"]
    }}
    ruby {{
        code => '
               require "securerandom"
               parsed_json= JSON.parse(event.get("message"))
               pri=         (16 * 8) + 2
               ver=         event.get("@version")
               ts=          event.get("@timestamp").time.strftime("%Y-%m-%d %H:%M:%S")
               hos=         format("%s:%d/%s",event.get("host"),event.get("port"),parsed_json["__SId"])
               sr=          "KongHTTP"
               pid=         "TODO"
               msg=         SecureRandom.uuid
               txt=         event.get("message")
               event.set("message",format("<%d>%s %s %s %s %s %s %s",pri,ver,ts,hos,sr,pid,msg,txt))
        '
    }}
}}
output {{
    stdout {{
        codec => plain {{
            format => "%{{message}}"
        }}
    }}
    tcp {{
        host => "127.0.0.1"
        port => {manager_agent_port}
    }}
    # 2024-10-24T07:09:01.500Z ip-172-28-0-1.eu-west-1.compute.internal KongHTTP "{\"service\":{\"name\":\"aaaaaaaa\"}}"
    # Optionally, you can send to S3 or other outputs
    # s3 {{
    #   access_key_id => "YOUR_AWS_ACCESS_KEY"
    #   secret_access_key => "YOUR_AWS_SECRET_KEY"
    #   bucket => "your-s3-bucket-name"
    #   region => "your-region"
    #   time_file => 5
    #   prefix => "logs/"
    # }}
}}
#<130>1 2024-10-28 10:31:07 aaaaaaaa KongHTTP a1bf4b20-adf8-4a35-a282-b953cd6c998e PID {"__SId":"aaaaaaaa"}
